### ISSUE TITLE
Node Gyp should not assume installation path: `/usr/local/share/verilator/include`

### ISSUE THREAD

**Issue by drom** [ameetgohil/signalflip-js#8]
You should not assume that Verilator is installed globally this way.
https://www.veripool.org/projects/verilator/wiki/Installing
Look at the README file in the source:
https://github.com/sifive/verilator/blob/master/README.pod#installation

**Comment by ameetgohil** [comment]
Switched to cmake and the package uses the VERILATOR_ROOT environment variable if it set. Otherwise will default to /usr/local/share/verilator
